### PR TITLE
Gorest2021 issue 6

### PR DESCRIPTION
**Pull request by sierra-moxon**
- bypass barista call in favor of using the pre-computed JSON files that represent gocams here: https://go-public.s3.amazonaws.com/files/go-cam/ 
- fixes https://github.com/geneontology/api-gorest-2021/issues/6

### CODE REVIEW

**Review by kltm — APPROVED** [review]
Add routes and tests; simple bypass to static models

**Comment by kltm** [comment]
Not sure about the failed tests, but I'm happy to have these self-merged when done.

**Comment by pkalita-lbl** [comment]
Is there a convention to accept either prefixed (`gomodel:568b0f9600000284`) or bare (`568b0f9600000284`) or both? I think as it stands this will only accept bare IDs.

**Comment by kltm** [comment]
Interesting question. I am more comfortable using All CURIEs All The Time, but I understand the original intent of having the ID sans-namespace, as it is already in a GO-CAM route. I guess ideally both at this point then?

**Comment by sierra-moxon** [comment]
sure; I can add support for `gomodel:` prefixed ids.

**Pull request merged**
