### PR TITLE
handling cloudflare

### PR DESCRIPTION
**Pull request by abessiari**
Handling support for Cloudflare. it is optional.

### CODE REVIEW

**Comment by abessiari** [comment]
@kltm @sierra-moxon 

FYI: The handling of Clouldflare is mainly in the the apache proxy image (v6)

GITHUB
https://github.com/geneontology/devops-apache-proxy

DOCKERHUB:
https://hub.docker.com/repository/docker/geneontology/apache-proxy/general

**Comment by sierra-moxon** [comment]
Hi @abessiari - I am not sure why this doesn't automatically try and merge in main changes and re-run the tests (I fixed up the tests that have been failing this afternoon).  Could you please merge main into your fork and push the changes up so we can confirm that the tests pass again with these changes? 

(I also gave you branch permission on this repo, as even with the "Maintainers are allowed to edit this pull request" setting enabled, thank you, I can't see an easy way to force a main branch merge here without forking off your fork).

**Review by sierra-moxon — CHANGES_REQUESTED** [review]
please merge main in and confirm the tests are passing.

**Comment by abessiari** [comment]
@sierra-moxon 
The tests passed.

**Pull request merged**
